apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: voice-developers-role-binding
  namespace: voice-sandbox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: voice-sandbox
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: voice-developers
  namespace: voice-sandbox
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: voice-developers-role-binding
  namespace: voice-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: voice-dev
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: voice-developers
  namespace: voice-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: voice-developers-role-binding
  namespace: voice-stage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: voice-stage
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: voice-developers
  namespace: voice-stage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: voice-developers-role-binding
  namespace: voice-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: voice-prod
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: voice-developers
  namespace: voice-prod
