apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-controller
  namespace: stats
spec:
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: "3.33.0"
  values:
    fullnameOverride: "stats-ingress-nginx"
    controller:
      name: ingress-stats
      ingressClass: stats # Value used for selecting Ingress objects
      scope:
        enabled: true
        namespace: stats
      kind: Deployment
      autoscalig: 
        enabled: false
      replicaCount: 1
      addHeaders:
        X-Frame-Options: "DENY"
        X-Content-Type-Options: "nosniff"
        X-XSS-Protection: "1; mode=block"
        Strict-Transport-Security: "max-age=31536000"

      service:
        targetPorts:
          https: http
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:058419420086:certificate/07ec3379-0729-4b0e-9a9d-b27d179b0b4d
          service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS-1-2-2017-01
      config:
        use-forwarded-headers: "true"
        ssl-redirect: "true"
        force-ssl-redirect: "true"
    defaultBackend:
      enabled: false
