apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-controller
  namespace: voice-stage
spec:
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: "3.33.0"
  values:
    fullnameOverride: "voice-stage-ingress-nginx"
    controller:
      addHeaders:
        X-Frame-Options: "DENY"
        X-Content-Type-Options: "nosniff"
        X-XSS-Protection: "1; mode=block"
        Strict-Transport-Security: "max-age=31536000"
      config:
        use-forwarded-headers: "true"
        ssl-redirect: "true"
        force-ssl-redirect: "true"
        enable-underscores-in-headers: "true"
      ingressClass: voice-stage # Value used for selecting Ingress objects
      kind: Deployment
      replicaCount: 1
      scope:
        enabled: true
        namespace: voice-stage
      service:
        targetPorts:
          https: http
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:058419420086:certificate/3c6cf764-1e6f-44ad-bd81-cb92737bb410
          service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS-1-1-2017-01
    defaultBackend:
      enabled: false
