apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-controller
  namespace: voice-stage
spec:
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: nginx-ingress
    version: 1.31.0
  values:
    controller:
      name: ingress-voice-stage
      ingressClass: voice-stage # Value used for selecting Ingress objects
      scope:
        enabled: true
        namespace: voice-stage
      kind: Deployment
      autoscalig: 
        enabled: false
      replicaCount: 1
      addHeaders:
        X-Frame-Options: "DENY"
        X-Content-Type-Options: "nosniff"
        X-XSS-Protection: "1; mode=block"
        Strict-Transport-Security: "max-age=31536000"

      service:
        targetPorts:
          https: http
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:058419420086:certificate/8bc7b059-ab60-4e4c-9196-40f65754a7fe
      config:
        use-forwarded-headers: "true"
        ssl-redirect: "true"
        force-ssl-redirect: "true"

    defaultBackend:
      enabled: false
