apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: voice-dev
  name: voice-redirect
  annotations:
    kubernetes.io/ingress.class: "voice-dev"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
        return 302 https://dev.commonvoice.allizom.org$request_uri;
spec:
  rules:
  - host: voice-dev.allizom.org
