apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: voice-sandbox
  name: voice-redirect
  annotations:
    kubernetes.io/ingress.class: "voice-sandbox"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      return 302 https://sandbox.commonvoice.allizom.org$request_uri;
spec:
  rules:
  - host: voice-sandbox.allizom.org
