apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-controller
  namespace: voice-sandbox
spec:
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: "3.33.0"
  values:
    fullnameOverride: "voice-sandbox-ingress-nginx"
    controller:
      ingressClass: voice-sandbox # Value used for selecting Ingress objects
      scope:
        enabled: true
        namespace: voice-sandbox
      kind: Deployment
      replicaCount: 1
      addHeaders:
        X-Frame-Options: "DENY"
        X-Content-Type-Options: "nosniff"
        X-XSS-Protection: "1; mode=block"
        Strict-Transport-Security: "max-age=31536000"
      service:
        targetPorts:
          https: http
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:058419420086:certificate/a5c5ece0-fd82-4e79-8c0d-86f335168dc4
          service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS-1-1-2017-01
      config:
        use-forwarded-headers: "true"
        ssl-redirect: "true"
        force-ssl-redirect: "true"
        enable-underscores-in-headers: "true"

    defaultBackend:
      enabled: false
