apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: voice-prod
  name: voice-redirect
  annotations:
    kubernetes.io/ingress.class: "voice-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
        return 302 https://commonvoice.mozilla.org$request_uri;
    nginx.ingress.kubernetes.io/server-snippet: |
      location /firefox-voice {
        if ($http_x_forwarded_proto = 'http') {
          rewrite ^ https://$host$request_uri? permanent;
        }
        add_header Content-Security-Policy "default-src 'none'; connect-src https://www.google-analytics.com https://sentry.prod.mozaws.net; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.googleapis.com; script-src 'self' https://www.google-analytics.com; img-src 'self' data:; child-src https://www.youtube.com" ;
        proxy_pass https://mozilla-extensions.github.io/firefox-voice/homepage;
      }
spec:
  rules:
  - host: voice.mozilla.org
