apiVersion: v1
kind: Service
metadata:
  name: voice
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:058419420086:certificate/8bc7b059-ab60-4e4c-9196-40f65754a7fe
