apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kubernetes-external-secrets
  namespace: kube-system
spec:
  releaseName: kubernetes-external-secrets
  skipCRDs: true
  chart:
    repository: https://godaddy.github.io/kubernetes-external-secrets/
    name: kubernetes-external-secrets
    version: 4.0.0
  values:
    securityContext:
      fsGroup: 65534
    serviceAccount:
      name: "kubernetes-external-secrets"
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::058419420086:role/voice-prod-kubernetes-external-secrets"
